apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: adservice
    newName: 253343486660.dkr.ecr.ap-southeast-4.amazonaws.com/adservice
    newTag: "1.0.0"     # Initial version, will be updated by Jenkins CI

  - name: cartservice
    newName: 253343486660.dkr.ecr.ap-southeast-4.amazonaws.com/cartservice
    newTag: "1.0.0"

  - name: checkoutservice
    newName: 253343486660.dkr.ecr.ap-southeast-4.amazonaws.com/checkoutservice
    newTag: "1.0.0"

  - name: currencyservice
    newName: 253343486660.dkr.ecr.ap-southeast-4.amazonaws.com/currencyservice
    newTag: "1.0.0"

  - name: emailservice
    newName: 253343486660.dkr.ecr.ap-southeast-4.amazonaws.com/emailservice
    newTag: "1.0.0"

  - name: frontend
    newName: 253343486660.dkr.ecr.ap-southeast-4.amazonaws.com/frontend
    newTag: "1.0.0"

  - name: paymentservice
    newName: 253343486660.dkr.ecr.ap-southeast-4.amazonaws.com/paymentservice
    newTag: "1.0.0"

  - name: productcatalogservice
    newName: 253343486660.dkr.ecr.ap-southeast-4.amazonaws.com/productcatalogservice
    newTag: "1.0.0"

  - name: recommendationservice
    newName: 253343486660.dkr.ecr.ap-southeast-4.amazonaws.com/recommendationservice
    newTag: "1.0.0"

  - name: shippingservice
    newName: 253343486660.dkr.ecr.ap-southeast-4.amazonaws.com/shippingservice
    newTag: "1.0.0"

  - name: redis-cart
    newName: 253343486660.dkr.ecr.ap-southeast-4.amazonaws.com/redis-cart
    newTag: "1.0.0"